/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
/**
 * -- 异步读取 CSV 文件第一列的日期值，返回字符串数组
 * -- limit: 可选参数，若提供则返回最后 n 个值
 */
export declare function getTradingCalendar(filePath: string, limit?: number | undefined | null): Promise<Array<string>>
